# Generated by Django 2.2.1 on 2019-06-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Descripción')),
                ('address', models.CharField(max_length=128, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciónes',
            },
        ),
    ]
