# Generated by Django 2.2.1 on 2019-06-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', 'dayofweek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistance',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha'),
        ),
        migrations.RemoveField(
            model_name='person',
            name='address',
        ),
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Dirección'),
        ),
        migrations.RemoveField(
            model_name='relative',
            name='address',
        ),
        migrations.AddField(
            model_name='relative',
            name='address',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Dirección'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
