# Generated by Django 2.2.1 on 2019-06-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_dwelling'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=128, verbose_name='Apellido')),
                ('date_of_birth', models.DateField(verbose_name='Fecha de nacimiento')),
                ('dni', models.IntegerField(unique=True, verbose_name='DNI')),
                ('civil_status', models.IntegerField(choices=[(0, 'Soltero/a'), (1, 'Casado/a'), (2, 'Divorciado/a'), (4, 'Viudo/a')], default=0)),
                ('address', models.ManyToManyField(blank=True, related_name='person', to='management.Address')),
                ('dwelling', models.ManyToManyField(blank=True, related_name='person', to='management.Dwelling')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
    ]
