# Generated by Django 2.2.1 on 2019-06-08 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='VCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_card', models.CharField(choices=[('email', 'Email'), ('phone', 'Teléfono')], max_length=20, verbose_name='Tipo de dato')),
                ('data', models.CharField(max_length=128, verbose_name='Valor')),
                ('upload_date', models.DateTimeField(auto_now=True, verbose_name='Last change')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vcards', to='management.Person')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
            },
        ),
    ]
