# Generated by Django 2.2.1 on 2019-06-08 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_relative'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('relative_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='management.Relative')),
                ('type', models.IntegerField(choices=[(1, 'Pareja'), (0, 'Hermano')], default=0, verbose_name='Familiar')),
                ('date_of_birth', models.DateField(verbose_name='Fecha de nacimiento')),
            ],
            options={
                'verbose_name': 'Familia',
                'verbose_name_plural': 'Familias',
            },
            bases=('management.relative',),
        ),
        migrations.AddField(
            model_name='person',
            name='is_healthy',
            field=models.BooleanField(default=False, verbose_name='Problema de salud'),
        ),
        migrations.AddField(
            model_name='person',
            name='is_medicated',
            field=models.BooleanField(default=False, verbose_name='Toma medicación'),
        ),
        migrations.AddField(
            model_name='person',
            name='which_issue',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Cual?'),
        ),
        migrations.AddField(
            model_name='person',
            name='which_medicated',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Cual?'),
        ),
        migrations.DeleteModel(
            name='Sibling',
        ),
        migrations.AddField(
            model_name='family',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sibling', to='management.Person'),
        ),
    ]
