# Generated by Django 2.2.1 on 2019-06-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_alter_relative'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='dropout_reason',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Motivo de abandono'),
        ),
        migrations.AddField(
            model_name='person',
            name='education_stage',
            field=models.IntegerField(choices=[(0, 'Jardin'), (1, 'Primaria'), (2, 'Secundario'), (3, 'Universidad')], default=0, verbose_name='Nivel eductivo alcazado'),
        ),
        migrations.AddField(
            model_name='person',
            name='is_baptized',
            field=models.BooleanField(default=False, verbose_name='Esta bautizado?'),
        ),
        migrations.AddField(
            model_name='person',
            name='is_communion',
            field=models.BooleanField(default=False, verbose_name='Hijo la comunion '),
        ),
        migrations.AddField(
            model_name='person',
            name='is_confirmation',
            field=models.BooleanField(default=False, verbose_name='Hizo la confirmacion'),
        ),
        migrations.AddField(
            model_name='person',
            name='religion',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Religion que practica'),
        ),
        migrations.AlterField(
            model_name='person',
            name='civil_status',
            field=models.IntegerField(choices=[(0, 'Soltero/a'), (1, 'Casado/a'), (2, 'Divorciado/a'), (3, 'Viudo/a')], default=0, verbose_name='Estado civil'),
        ),
    ]
