# Generated by Django 2.2.1 on 2019-06-08 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_alter_relative'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='son',
            name='parent',
        ),
        migrations.AddField(
            model_name='son',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sons', to='management.Person'),
        ),
    ]
