# Generated by Django 2.2.1 on 2019-06-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_alter_son'),
    ]

    operations = [
        migrations.AddField(
            model_name='son',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='son',
            name='education_stage',
            field=models.IntegerField(choices=[(0, 'Jardin'), (1, 'Primaria'), (2, 'Secundario')], default=0, verbose_name='Nivel eductivo alcazado'),
        ),
    ]
