# Generated by Django 2.2.1 on 2019-06-08 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_add_education_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='son',
            name='date_of_birth',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
    ]
