# Generated by Django 2.2.1 on 2019-06-09 03:31

from django.db import migrations, models


def create_days_of_week(apps, schema_editor):
    days = [
        'Lunes',
        'Martes',
        'Miercoles',
        'Jueves',
        'Viernes',
        'Sábado',
        'Domingo']

    DayOfWeek = apps.get_model('management', 'DayOfWeek')
    for day in days:
        try:
            DayOfWeek.objects.create(name=day).save()
        except BaseException:
            print(f'Already exits {day}')


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_unique'),
    ]

    operations = [
        migrations.RunPython(create_days_of_week),
    ]
