# Generated by Django 2.2.1 on 2019-06-04 20:07

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(
                    max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(
                    blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(
                    max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(
                    max_length=50, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254,
                                            unique=True, verbose_name='Email address')),
                ('confirmed_email', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(
                    default=False, verbose_name='staff status')),
                ('is_superuser', models.BooleanField(
                    default=False, verbose_name='superuser status')),
                ('is_active', models.BooleanField(
                    default=True, verbose_name='active')),
                ('date_joined', models.DateTimeField(
                    auto_now_add=True, verbose_name='date joined')),
                ('date_updated', models.DateTimeField(
                    auto_now=True, verbose_name='date updated')),
                ('activation_key', models.UUIDField(
                    default=uuid.uuid4, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
