# Generated by Django 2.2.1 on 2019-06-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190608_1729'),
    ]

    operations = [
    ]
