# Generated by Django 2.2.1 on 2019-06-08 20:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('body', ckeditor.fields.RichTextField(verbose_name='Contenido')),
                ('cover_image', models.ImageField(upload_to='blog/posts/cover_images', verbose_name='Imagen de portada')),
            ],
            options={
                'verbose_name': 'Publicación',
                'verbose_name_plural': 'Publicaciones',
            },
        ),
    ]
